### ISSUE TITLE
Commands seem to do nothing

### ISSUE THREAD

**Issue by atticusmatticus** [cainhooow/drkryz-roundedtabs#1]
Hey, I love this idea for an extension. the squared tabs have always bugged me. 

I have tried running the commands `drkryz-roundedtabs.configure_now` and the one that pops up in the ⌘+⇧+P menu "roundedtabs: Configure Theme" but nothing seems to happen. I don't get a prompt for password either. 

I'm on macOS 14.3

**Comment by cainhooow** [comment]
Hello, thanks for the comment! At the moment there is no implementation for MacOS but with this comment I feel encouraged to implement it!

**Comment by atticusmatticus** [comment]
Oh alright. Well I'd love to see it for macOS when you implement! Thanks!

**Comment by cainhooow** [comment]
As I don't have a MacOS, I have no idea how directories work, maybe it's like Linux but I also wouldn't know how to test it precisely because I don't have a MacOS, but I appreciate the comment and I'll try to implement it

**Comment by atticusmatticus** [comment]
It's typically similar to Linux but yeah I don't know for sure. I'd be happy to help though I don't know much about CSS.

**Comment by cainhooow** [comment]
I sent a new version (v0.2.3) that implements the function for macOS, but I'm not sure if it will work, the version being released in vscode you can test and see some error output on the screen, if so.

**Comment by atticusmatticus** [comment]
It looks like I get two errors/warnings:
```
Error executing sudo command: Error: Command failed: echo ****** | sudo -S cp /Users/***/.vscode/extensions/drkryz.drkryz-roundedtabs-0.2.3/dist/Users/***/.vscode/extensions/drkryz.drkryz-roundedtabs-0.2.3/dist/css/workbench.desktop.mod.css /Applications/Visual Studio Code.app/Contents/Resouces/app/out/vs/workbench/workbench.desktop.main.css Password:Sorry, try again. Password: sudo: no password was provided sudo: 1 incorrect password attempt
```
This one seems to be saying that my sudo password is incorrect but I have checked a couple times now and it is correct.

```
Please, provide a valid installation path of vscode
```
At the moment I'm giving it the path to vscode in my Applications folder. Not sure if spaces need to be escaped but it seems to fail either way:
1. `/Applications/Visual\ Studio\ Code.app`
2. `/Applications/Visual Studio Code.app`

**Comment by cainhooow** [comment]
Hello, I'll check the errors.. It could be some logic problems hahaha it's difficult to do it blindly!

**Comment by atticusmatticus** [comment]
Of course! I appreciate you trying. I'm happy to help however I can.

**Comment by cainhooow** [comment]
Hello again :) Could you test version 0.2.4 and see if any output is generated. With the error report you sent previously I was able to create an idea of how directories work on macos

And if you can try 0.2.6 too, which includes some fixes for the path, but I didn't handle the mac path correctly, it should be fine now!

If the problem persists, even if these fixes are to try to resolve the problem, I will try to get a Mac so I can do some tests and be able to implement with more certainty!

**Comment by atticusmatticus** [comment]
```
Error executing sudo command: Error: Command failed: echo ******** | sudo -S cp /Users/***/.vscode/extensions/drkryz.drkryz-roundedtabs-0.2.7/dist/css/workbench.desktop.mod.css Password:cp: missing destination file operand after '/Users/***/.vscode/extensions/drkryz.drkryz-roundedtabs-0.2.7/dist/css/workbench.desktop.mod.css' Try 'cp --help' for more information.
```
Am I supposed to point it to the .app directory in `/Applications` or some executable therein?

**Comment by cainhooow** [comment]
No, just the vscode base directory! The rest the code was made to handle. I'll look into more details! I got (or maybe) a system with Mac!

**Comment by atticusmatticus** [comment]
Great to hear. Thank you!

**Comment by cainhooow** [comment]
Hello! I tested it and now everything appears to be correct! can update to version 0.3.2. I'm waiting for a response and if it worked, I'd be grateful for the issue!

**Comment by atticusmatticus** [comment]
It works! thanks :)
