### ISSUE TITLE
Error executing sudo command: Error: Command failed:

### ISSUE THREAD

**Issue by ANAKARABILAL** [cainhooow/drkryz-roundedtabs#2]
Hi I'm just  trying to activate the Extension but I always get the same issue `Error executing sudo command: Error: Command failed: echo Bilal | sudo -S cp /home/bilal574858/.vscode/extensions/drkryz.drkryz-roundedtabs-0.3.2/dist/css/workbench.desktop.mod.css cp: missing destination file operand after '/home/bilal574858/.vscode/extensions/drkryz.drkryz-roundedtabs-0.3.2/dist/css/workbench.desktop.mod.css' Try 'cp --help' for more information.`  so  i tried to see if the vscode path was the wrong one with `which code` and i get `/usr/bin/code` that's what i put
by the way the extension seems incredible I hope I can make this work. I don't like that squared  things

**Comment by cainhooow** [comment]
Hello, About the path, `/usr/bin/code` is just the path of the vscode binary, you need to provide the vscode installation path where it contains the content for it to work. Generally this binary calls the vscode "executable". Check the vscode installation, whether it was installed by flatpak or via a system package manager. Thanks!
